# Generated by Django 6.0.5 on 2026-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprendiz', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('Academica', 'Académica'), ('Administrativa', 'Administrativa')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completada', 'Completada')], default='Pendiente', max_length=20)),
            ],
        ),
    ]
